### ISSUE TITLE
Adding reply-to option

### ISSUE THREAD

**Issue by Youans** [Youans/nodejs-nodemailer-outlook#6]
Adding reply-to option reference https://nodemailer.com/message/

**Comment by Hardenberg** [comment]
I'm currently missing this feature.
Can I help you with this? or vote for it?

**Comment by gazambuja** [comment]
+1

**Comment by r0zar** [comment]
+1

**Comment by r0zar** [comment]
I was able to get this working in a fork of the project.

**Comment by r0zar** [comment]
Although both `sender` and `from` don't seem to work, my theory is office365 has a limitation on that.

**Comment by x-077** [comment]
@r0zar , could you do a pull request ?

**Comment by x-077** [comment]
Hello @Youans, 

Do you think you can review this pull request ? 

Thanks @r0zar

Thanks by advance.

**Comment by Youans** [comment]
Fixed in version v1.2.0
