### ISSUE TITLE
Not receiving the mails

### ISSUE THREAD

**Issue by iAssureIT** [Youans/nodejs-nodemailer-outlook#8]
Hi There,

I am having following code base :

var nodeoutlook = require('nodejs-nodemailer-outlook');
app.post('/send-email', (req, res)=> {
	nodeoutlook.sendEmail({
    auth: {
        user: "abc@mydomain.in",
        pass: "***********"
    },
    from: 'abc@mydomain.in',
    to: 'receiver@gmail.com',
    subject: 'Hey you, awesome!',
    html: '<b>This is bold text</b>',
    text: 'This is text version!',
    
    onError: (e) => console.log('e',e),
    onSuccess: (i) => console.log('i',i)
}

I am getting following output:

i { accepted: [ 'anagha.sinless@gmail.com' ],
  rejected: [],
  envelopeTime: 372,
  messageTime: 519,
  messageSize: 571,
  response:
   '250 2.0.0 OK <0a9f3eef-1c74-140d-f3ba-7c25c5049f60@riskpro.in> [Hostname=PS2PR06MB3510.apcprd06.prod.outlook.com]',
  envelope:
   { from: 'abc@mydomain.in',
     to: [ 'recevier@gmail.com' ] },
  messageId: '<0a9f3eef-1c74-140d-f3ba-7c25c5049f60@riskpro.in>' }
POST /send-email - - ms - -

Please let me know whats wrong.

THanks in advance.

**Comment by Youans** [comment]
Hi iAssureIT,
I see nothing wrong accepted means that your email is already sent
However I can suggest to check junk or spam folder maybe your domain is not well recognized by google servers
